/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2021-07-15 13:38:29
 */


#ifndef APPLICATION_H
#define APPLICATION_H

#include <BCDS_Retcode.h>
#include "applicationTypes.h"


Retcode_T initGlobalVariables_application();

#endif
