/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2021-09-13 13:23:50
 */


#ifndef CONNECTIVITYMQTT_MQTT_H
#define CONNECTIVITYMQTT_MQTT_H

#include <BCDS_Retcode.h>


/**
 * Sets up the MQTT.
 */
Retcode_T ConnectivityMQTTMessaging_Setup(void);

/**
 * Enables the MQTT sensor.
 */
Retcode_T ConnectivityMQTTMessaging_Enable(void);

/**
 * Provides read access to Test.
 */
Retcode_T ConnectivityMQTTMessaging_Test_Read(char** result);

/**
 * Provides write access to Test.
 */
Retcode_T ConnectivityMQTTMessaging_Test_Write(char** result);


#endif
