/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2021-09-13 13:23:50
 */


#ifndef CONNECTIVITYWLAN_WLAN_H
#define CONNECTIVITYWLAN_WLAN_H

#include <BCDS_Retcode.h>


/**
 * Sets up the WLAN.
 */
Retcode_T ConnectivityWLANMyWifiResource_Setup(void);

/**
 * Enables the WLAN sensor.
 */
Retcode_T ConnectivityWLANMyWifiResource_Enable(void);



#endif
