/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2021-09-13 13:23:50
 */


#include <FreeRTOS.h>
#include <BCDS_Basics.h>
#include <BCDS_CmdProcessor.h>
#include <timers.h>
#include <BCDS_Retcode.h>
#include "MitaTime.h"
#include "MitaExceptions.h"
#include "MitaEvents.h"

static TimerHandle_t timerHandleEvery1Second1;

static void InternalHandleEvery1Second1(TimerHandle_t xTimer)
{
	BCDS_UNUSED(xTimer);
	CmdProcessor_Enqueue(&Mita_EventQueue, HandleEvery1Second1, NULL, 0);
}


Retcode_T SetupTime(void)
{
	
	timerHandleEvery1Second1 = xTimerCreate("timerHandleEvery1Second1", UINT32_C(1000), pdTRUE, NULL, InternalHandleEvery1Second1);
	
	if(timerHandleEvery1Second1 == NULL)
	{
		return RETCODE(RETCODE_SEVERITY_ERROR, RETCODE_OUT_OF_RESOURCES);
	}
	
	return NO_EXCEPTION;
}

Retcode_T EnableTime(void)
{
	Retcode_T result = NO_EXCEPTION;

	
	result = EveryHandleEvery1Second1_Enable();
	if(result != NO_EXCEPTION)
	{
		return result;
	}
	
	return NO_EXCEPTION;
}

Retcode_T EveryHandleEvery1Second1_Enable(void)
{
	xTimerStart(timerHandleEvery1Second1, 0);
	
	return NO_EXCEPTION;
}


