/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2021-09-13 13:23:51
 */


#ifndef SENSORBUTTON_ONE_BUTTON_ONE_H
#define SENSORBUTTON_ONE_BUTTON_ONE_H

#include <BCDS_Retcode.h>


/**
 * Sets up the button_one.
 */
Retcode_T SensorButton_one_Setup(void);

/**
 * Enables the button_one sensor.
 */
Retcode_T SensorButton_one_Enable(void);



#endif
