/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2021-09-13 13:23:51
 */


#include <BCDS_Basics.h>
#include <BCDS_Retcode.h>
#include <string.h>
#include <inttypes.h>
#include <stdio.h>
#include <BCDS_LightSensor.h>
#include <stdint.h>
#include <XdkSensorHandle.h>
#include <BCDS_Environmental.h>
#include <stdbool.h>
#include "SensorLight.h"
#include "SensorEnvironment.h"
#include "ConnectivityMQTTMessaging.h"
#include "MitaExceptions.h"
#include "application.h"

#ifndef BCDS_MODULE_ID
#define BCDS_MODULE_ID 0xCAFE
#endif

double tempCorrection = 6.5975f;

Retcode_T initGlobalVariables_application() {
	Retcode_T exception = RETCODE_OK;
	
	if(exception != NO_EXCEPTION) return exception;
	
	return exception;
}

Retcode_T HandleEveryButton_onePressed1(void* userParameter1, uint32_t userParameter2)
{
	
	BCDS_UNUSED(userParameter1);
	BCDS_UNUSED(userParameter2);

	Retcode_T exception = NO_EXCEPTION;
	
	
	char* _newConnectivityMQTTMessaging_Test_1 = "Test Write";
	exception = ConnectivityMQTTMessaging_Test_Write(&_newConnectivityMQTTMessaging_Test_1);
	if(exception != NO_EXCEPTION) return exception;


	return NO_EXCEPTION;
}

Retcode_T HandleEvery1Second1(void* userParameter1, uint32_t userParameter2)
{
	
	BCDS_UNUSED(userParameter1);
	BCDS_UNUSED(userParameter2);

	Retcode_T exception = NO_EXCEPTION;
	
	
	Environmental_Data_T sensorEnvironmentModalityPreparation_1;
	exception = Environmental_readData(xdkEnvironmental_BME280_Handle, &sensorEnvironmentModalityPreparation_1);
	if(exception != NO_EXCEPTION) return exception;
	
	uint32_t humi;
	humi = sensorEnvironmentModalityPreparation_1.humidity;
	double pres = sensorEnvironmentModalityPreparation_1.pressure / 1000.0f;
	double temp = sensorEnvironmentModalityPreparation_1.temperature / 1000.0f;
	uint32_t sensorLightModalityPreparation_2;
	exception = LightSensor_readLuxData(xdkLightSensor_MAX44009_Handle, &sensorLightModalityPreparation_2);
	if(exception != NO_EXCEPTION) return exception;
	
	double light = sensorLightModalityPreparation_2 / 1000.0f;
	temp = temp - tempCorrection;
	char result1328123711_buf[95] = {0};
	char *result1328123711 = result1328123711_buf;
	
	char mainHandleEvery1Second12Result1328123711_6_buf[95] = {0};
	snprintf(mainHandleEvery1Second12Result1328123711_6_buf, sizeof(mainHandleEvery1Second12Result1328123711_6_buf), "{\"data\":[{\"H\":%" PRIu32 ",\"P\":%.6g,\"T\":%.6g,\"L\":%.6g}]}", humi, pres, temp, light);
	memcpy(result1328123711, mainHandleEvery1Second12Result1328123711_6_buf, sizeof(mainHandleEvery1Second12Result1328123711_6_buf));
	
	char* _newConnectivityMQTTMessaging_Test_1 = result1328123711;
	exception = ConnectivityMQTTMessaging_Test_Write(&_newConnectivityMQTTMessaging_Test_1);
	if(exception != NO_EXCEPTION) return exception;


	return NO_EXCEPTION;
}


